name: Pr Checker

on: pull_request

jobs:
  check:
    name: check ref_name on PR
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.ref_name }}
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
    
